### ISSUE TITLE
今天插件的弹出菜单换行出现了格式问题

### ISSUE THREAD

**Issue by TenkoMitsuki** [TyraelDLee/HarukaEmoji#12]
![image](https://github.com/TyraelDLee/HarukaEmoji/assets/158137695/dc6a0d35-1c08-432f-b1ce-930f3a1feab2)
Chrome

**Comment by TenkoMitsuki** [comment]
大概是滚动条变粗了挤到了……说来能不能改改插件的默认设置？自动打卡默认开启，每次第一次装插件的时候就会自动群发点亮所有牌子。而开播通知的【显示封面】项每次重启服务就会自动off

**Comment by TyraelDLee** [comment]
这个问题现在已经修复啦，感谢你提交这个问题！

**Comment by TyraelDLee** [comment]
默认设置会再下一次更新改为默认关闭
