### ISSUE TITLE
开启rua豹器后，导致哔哩哔哩的评论输入框下的“表情”按钮点击后无法正常打开

### ISSUE THREAD

**Issue by yangdongdong333** [TyraelDLee/HarukaEmoji#3]
开启rua豹器后，导致哔哩哔哩的评论输入框下的“表情”按钮点击后无法正常打开
![QQ截图20220918132722](https://user-images.githubusercontent.com/49440819/190887161-2f0f9a4b-3f8e-449a-adbe-0c414a38481f.png)

**Comment by TyraelDLee** [comment]
代码应该是修好了，考完试细细查完后马上打包；；

**Comment by TyraelDLee** [comment]
5.14版应该修好了
