### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by loverocksugar** [TyraelDLee/HarukaEmoji#7]
有一部分没有打卡成功
报错：
AbortError: The user aborted a request. at function queryLivingRoom(); line 500
AbortError: The user aborted a request. at function dynamicNotify(); line 875
AbortError: The user aborted a request. at function videoNotify(); line 934

**Comment by HappySugerLife** [comment]
是不是账号注销的牌子影响了？我删牌子了，在重启服务，还是一直报错，有五个没打卡，Google浏览器是最新版

**Comment by TyraelDLee** [comment]
账号注销不应该影响的，上面那几个错误是网络问题导致的但是不是打卡功能相关的，是5个固定直播间没打卡嘛，有些直播间会把打卡设为屏蔽词导致打卡失败

**Comment by HappySugerLife** [comment]
好的，有自定义打卡词吗？这个功能你看可以加吗

**Comment by TyraelDLee** [comment]
好的，下个版本给加上
